"""empty message

Revision ID: 32456bbcfaaa
Revises: 81f92663bedf
Create Date: 2022-07-06 23:28:25.790973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32456bbcfaaa'
down_revision = '81f92663bedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Inventory', sa.Column('item_returned', sa.String(length=100), nullable=True))
    op.add_column('Inventory', sa.Column('refunded_amount', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Inventory', 'refunded_amount')
    op.drop_column('Inventory', 'item_returned')
    # ### end Alembic commands ###
