"""empty message

Revision ID: 81f92663bedf
Revises: 
Create Date: 2022-07-06 23:12:30.126672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f92663bedf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Inventory', sa.Column('amazon_asin', sa.String(length=100), nullable=True))
    op.add_column('Inventory', sa.Column('retailer_asin', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Inventory', 'retailer_asin')
    op.drop_column('Inventory', 'amazon_asin')
    # ### end Alembic commands ###
