"""empty message

Revision ID: 82028ff2a3b7
Revises: 32456bbcfaaa
Create Date: 2022-07-24 17:51:04.481262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82028ff2a3b7'
down_revision = '32456bbcfaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Inventory', sa.Column('order_number', sa.String(length=100), nullable=True))
    op.add_column('Inventory', sa.Column('order_date', sa.String(length=100), nullable=True))
    op.add_column('Inventory', sa.Column('bndl_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Inventory', 'bndl_qty')
    op.drop_column('Inventory', 'order_date')
    op.drop_column('Inventory', 'order_number')
    # ### end Alembic commands ###
