"""empty message

Revision ID: c6499a8424d5
Revises: 82028ff2a3b7
Create Date: 2022-08-13 13:34:48.692002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6499a8424d5'
down_revision = '82028ff2a3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Inventory', sa.Column('rebate_used', sa.String(length=100), nullable=True))
    op.add_column('Inventory', sa.Column('destination', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Inventory', 'destination')
    op.drop_column('Inventory', 'rebate_used')
    # ### end Alembic commands ###
